### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#1]
Getting this message when trying to run the script

C:\Users\Administrator\Desktop\pyBEscanner>pyBEscanner.py

Reloading Config
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 161, in
 <module>
    pyBE.start()
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 120, in
 start
    self.loadconfig()
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 56, in
loadconfig
    default["OffSet"] = self.config.get("Default", "OffSet")
  File "C:\Python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'offset' in section: 'Default'

**Comment by k4n30** [comment]
Issue resolved with help from Torndeco :)
