### ISSUE TITLE
Kick code not working

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#60]
Getting alot of these:

Scanning .Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 296, in <module>
    main.start()
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 252, in start
    logs_battleye.Scanner(server).scan()
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 216, in scan
    self.scan_battleye_logs(log)
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 121, in scan_battleye_logs
    self.update_kicks(x, self.log_scanner.kicklist, update=True)
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 181, in update_kicks
    self.kicks.synckicks()
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 424, in synckicks
    with open(self.kicks_file, "a", encoding='utf8') as f_kicks:
TypeError: 'encoding' is an invalid keyword argument for this function

Issue with filters or code?

**Comment by Torndeco** [comment]
Should be fixed now, was part of code from pyBEscanner & forgot to remove the encoding option from open kicks file
