### ISSUE TITLE
UnboundLocalError: local variable 'ban_time' referenced before assignment

### ISSUE THREAD

**Issue by wriley** [Torndeco/pyBEscanner#73]
I get this stack trace when pyBEscanner reloads bans.

Windows 7, Python 2.7, pyBEscanner from yesterday

``` python
Scanning ........
Reloading Bans: dayz_1.chernarus

Traceback (most recent call last):
  File "pyBEscanner.py", line 111, in <module>
    main.start()
  File "pyBEscanner.py", line 94, in start
    server_ban_deamon.writeBans(server["Server ID"])
  File "C:\pyBEscanner\modules\bans.py", line 57, in writeBans
    self.bans_server_list[servername]["Bans"].writeBans()
  File "C:\pyBEscanner\modules\bans.py", line 197, in writeBans
    ban_time = str(current_time + (int(ban_time) * 86400))
UnboundLocalError: local variable 'ban_time' referenced before assignment
```

**Comment by Torndeco** [comment]
Thx, should be fixed now
