### ISSUE TITLE
Error somewhere?

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#77]
---

```
   Loading Config File
```

---

Scanning .Traceback (most recent call last):
  File "C:\DayZ\pyBEscanner\pyBEscanner.py", line 111, in <module>
    main.start()
  File "C:\DayZ\pyBEscanner\pyBEscanner.py", line 67, in start
    logs_battleye.Scanner(server, server_ban_deamon).scan()
  File "C:\DayZ\pyBEscanner\modules\logs_battleye.py", line 249, in scan
    self.scan_battleye_logs(log)
  File "C:\DayZ\pyBEscanner\modules\logs_battleye.py", line 131, in scan_battleye_logs
    x)
  File "C:\DayZ\pyBEscanner\modules\logs_battleye.py", line 318, in scan_log
    ip_port = re.split(':', re.search("\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{1,4}[0-9]", line_stripped).group(0))
## AttributeError: 'NoneType' object has no attribute 'group'

Assuming it has to do with one of the regex rules

**Comment by Torndeco** [comment]
Its an error out that it can't get the players IP:Port from battleye logs

Its a weird one, if it happens again..
Need a copy of your pyBEscanner temp directory...
