### ISSUE TITLE
Error in latest commit

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#78]
---
## System Platform = Windows

---

```
   Loading Config File
```

---

Scanning .Traceback (most recent call last):
  File "C:\DayZ\pyBEscanner\pyBEscanner.py", line 109, in <module>
    main.start()
  File "C:\DayZ\pyBEscanner\pyBEscanner.py", line 71, in start
    logs_server.ConsoleScanner(server, player_tracker).scan_log(0)
  File "C:\DayZ\pyBEscanner\modules\logs_server.py", line 142, in **init**
    self.player_tracker = PlayerTracker(server_settings, self.logfile, player_tracker_data_file)
  File "C:\DayZ\pyBEscanner\modules\logs_server.py", line 63, in **init**
    self.resetData()
  File "C:\DayZ\pyBEscanner\modules\logs_server.py", line 67, in resetData
    self.save()
  File "C:\DayZ\pyBEscanner\modules\logs_server.py", line 102, in save
    with open(self.player_tracker_data_file, 'wb') as f_datafile:
## IOError: [Errno 13] Permission denied: 'C:\DayZ\Chernarus\dayz_1.chernarus\server.log'

Have had to turn off scan logs to get it to go away :(

**Comment by Torndeco** [comment]
Should be fixed now

**Comment by k4n30** [comment]
now getting this error with scan logs turned on:

Scanning .Traceback (most recent call last):
  File "C:\DayZ\pyBEscanner\pyBEscanner.py", line 109, in <module>
    main.start()
  File "C:\DayZ\pyBEscanner\pyBEscanner.py", line 71, in start
    logs_server.ConsoleScanner(server, player_tracker).scan_log(0)
  File "C:\DayZ\pyBEscanner\modules\logs_server.py", line 172, in scan_log
    playername, ip = self.get_player_ip(data)
  File "C:\DayZ\pyBEscanner\modules\logs_server.py", line 204, in get_player_ip
    ip = temp2[:-16] 
NameError: global name 'temp2' is not defined

Have no issues with scan logs turned off

**Comment by Torndeco** [comment]
Fixed it, hit another bug  sigh....
Disabled server log scanning altogether till i get it fixed...
